#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x1ffff
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 0x20
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 0x2

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_XBRAM_0_BASEADDR 0x0
#define XPAR_XBRAM_0_HIGHADDR 0x1ffff
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x2

#define XPAR_XEMC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_EMC_0 */
#define XPAR_AXI_EMC_0_BASEADDR 0x60000000
#define XPAR_AXI_EMC_0_HIGHADDR 0x61ffffff

/* Canonical definitions for peripheral AXI_EMC_0 */
#define XPAR_XEMC_0_BASEADDR 0x60000000
#define XPAR_XEMC_0_HIGHADDR 0x61ffffff

#define XPAR_XGPIO_NUM_INSTANCES 8

/* Definitions for peripheral INT_0_3 */
#define XPAR_INT_0_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_INT_0_3_BASEADDR 0x40070000
#define XPAR_INT_0_3_HIGHADDR 0x4007ffff
#define XPAR_INT_0_3_INTERRUPT_PRESENT 0x1
#define XPAR_INT_0_3_IS_DUAL 0x0
#define XPAR_INT_0_3_INTERRUPTS 0x2005
#define XPAR_FABRIC_INT_0_3_INTR 5
#define XPAR_INT_0_3_INTERRUPT_PARENT 0x41200001
#define XPAR_INT_0_3_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral INT_0_3 */
#define XPAR_XGPIO_0_BASEADDR 0x40070000
#define XPAR_FABRIC_XGPIO_0_INTR 5
#define XPAR_XGPIO_0_HIGHADDR 0x4007ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x4
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_0_IS_DUAL 0x0
#define XPAR_XGPIO_0_INTERRUPTS 0x2005
#define XPAR_XGPIO_0_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral BOARD_BUTTON */
#define XPAR_BOARD_BUTTON_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_BOARD_BUTTON_BASEADDR 0x40010000
#define XPAR_BOARD_BUTTON_HIGHADDR 0x4001ffff
#define XPAR_BOARD_BUTTON_INTERRUPT_PRESENT 0x0
#define XPAR_BOARD_BUTTON_IS_DUAL 0x0
#define XPAR_BOARD_BUTTON_GPIO_WIDTH 0x1

/* Canonical definitions for peripheral BOARD_BUTTON */
#define XPAR_XGPIO_1_BASEADDR 0x40010000
#define XPAR_XGPIO_1_HIGHADDR 0x4001ffff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x1
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

/* Definitions for peripheral BOARD_LED_2BITS */
#define XPAR_BOARD_LED_2BITS_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_BOARD_LED_2BITS_BASEADDR 0x40000000
#define XPAR_BOARD_LED_2BITS_HIGHADDR 0x4000ffff
#define XPAR_BOARD_LED_2BITS_INTERRUPT_PRESENT 0x0
#define XPAR_BOARD_LED_2BITS_IS_DUAL 0x0
#define XPAR_BOARD_LED_2BITS_GPIO_WIDTH 0x2

/* Canonical definitions for peripheral BOARD_LED_2BITS */
#define XPAR_XGPIO_2_BASEADDR 0x40000000
#define XPAR_XGPIO_2_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_2_GPIO_WIDTH 0x2
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_2_IS_DUAL 0x0

/* Definitions for peripheral BOARD_RGB */
#define XPAR_BOARD_RGB_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_BOARD_RGB_BASEADDR 0x40020000
#define XPAR_BOARD_RGB_HIGHADDR 0x4002ffff
#define XPAR_BOARD_RGB_INTERRUPT_PRESENT 0x0
#define XPAR_BOARD_RGB_IS_DUAL 0x0
#define XPAR_BOARD_RGB_GPIO_WIDTH 0x3

/* Canonical definitions for peripheral BOARD_RGB */
#define XPAR_XGPIO_3_BASEADDR 0x40020000
#define XPAR_XGPIO_3_HIGHADDR 0x4002ffff
#define XPAR_XGPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_3_GPIO_WIDTH 0x3
#define XPAR_XGPIO_3_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_3_IS_DUAL 0x0

/* Definitions for peripheral GPIO_A_0_6 */
#define XPAR_GPIO_A_0_6_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_GPIO_A_0_6_BASEADDR 0x40030000
#define XPAR_GPIO_A_0_6_HIGHADDR 0x4003ffff
#define XPAR_GPIO_A_0_6_INTERRUPT_PRESENT 0x0
#define XPAR_GPIO_A_0_6_IS_DUAL 0x0
#define XPAR_GPIO_A_0_6_GPIO_WIDTH 0x7

/* Canonical definitions for peripheral GPIO_A_0_6 */
#define XPAR_XGPIO_4_BASEADDR 0x40030000
#define XPAR_XGPIO_4_HIGHADDR 0x4003ffff
#define XPAR_XGPIO_4_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_4_GPIO_WIDTH 0x7
#define XPAR_XGPIO_4_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_4_IS_DUAL 0x0

/* Definitions for peripheral GPIO_B_0_6 */
#define XPAR_GPIO_B_0_6_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_GPIO_B_0_6_BASEADDR 0x40040000
#define XPAR_GPIO_B_0_6_HIGHADDR 0x4004ffff
#define XPAR_GPIO_B_0_6_INTERRUPT_PRESENT 0x0
#define XPAR_GPIO_B_0_6_IS_DUAL 0x0
#define XPAR_GPIO_B_0_6_GPIO_WIDTH 0x7

/* Canonical definitions for peripheral GPIO_B_0_6 */
#define XPAR_XGPIO_5_BASEADDR 0x40040000
#define XPAR_XGPIO_5_HIGHADDR 0x4004ffff
#define XPAR_XGPIO_5_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_5_GPIO_WIDTH 0x7
#define XPAR_XGPIO_5_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_5_IS_DUAL 0x0

/* Definitions for peripheral GPIO_C_0_6 */
#define XPAR_GPIO_C_0_6_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_GPIO_C_0_6_BASEADDR 0x40050000
#define XPAR_GPIO_C_0_6_HIGHADDR 0x4005ffff
#define XPAR_GPIO_C_0_6_INTERRUPT_PRESENT 0x0
#define XPAR_GPIO_C_0_6_IS_DUAL 0x0
#define XPAR_GPIO_C_0_6_GPIO_WIDTH 0x7

/* Canonical definitions for peripheral GPIO_C_0_6 */
#define XPAR_XGPIO_6_BASEADDR 0x40050000
#define XPAR_XGPIO_6_HIGHADDR 0x4005ffff
#define XPAR_XGPIO_6_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_6_GPIO_WIDTH 0x7
#define XPAR_XGPIO_6_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_6_IS_DUAL 0x0

/* Definitions for peripheral GPIO_D_0_6 */
#define XPAR_GPIO_D_0_6_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_GPIO_D_0_6_BASEADDR 0x40060000
#define XPAR_GPIO_D_0_6_HIGHADDR 0x4006ffff
#define XPAR_GPIO_D_0_6_INTERRUPT_PRESENT 0x0
#define XPAR_GPIO_D_0_6_IS_DUAL 0x0
#define XPAR_GPIO_D_0_6_GPIO_WIDTH 0x7

/* Canonical definitions for peripheral GPIO_D_0_6 */
#define XPAR_XGPIO_7_BASEADDR 0x40060000
#define XPAR_XGPIO_7_HIGHADDR 0x4006ffff
#define XPAR_XGPIO_7_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_7_GPIO_WIDTH 0x7
#define XPAR_XGPIO_7_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_7_IS_DUAL 0x0

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_KIND_OF_INTR 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IS_FAST 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_NUM_INTR_INPUTS 0x6
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_NUM_SW_INTR 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HAS_IVR 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HAS_CIE 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HAS_SIE 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HAS_IPR 0x1

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_HAS_IVR 0x1
#define XPAR_XINTC_0_HAS_CIE 0x1
#define XPAR_XINTC_0_HAS_SIE 0x1
#define XPAR_XINTC_0_HAS_IPR 0x1
#define XPAR_XINTC_0_IS_FAST 0x0
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_KIND_OF_INTR 0x0
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x6
#define XPAR_XINTC_0_NUM_SW_INTR 0x0

#define XPAR_XSPI_NUM_INSTANCES 1

/* Definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_AXI_QUAD_SPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_AXI_QUAD_SPI_0_BASEADDR 0x44a20000
#define XPAR_AXI_QUAD_SPI_0_HIGHADDR 0x44a2ffff
#define XPAR_AXI_QUAD_SPI_0_HASFIFOS 0x1
#define XPAR_AXI_QUAD_SPI_0_SLAVEONLY 0x0
#define XPAR_AXI_QUAD_SPI_0_NUM_SS_BITS 0x1
#define XPAR_AXI_QUAD_SPI_0_BITS_PER_WORD 0x8
#define XPAR_AXI_QUAD_SPI_0_SPI_MODE 0x2
#define XPAR_AXI_QUAD_SPI_0_AXI_INTERFACE 0x0
#define XPAR_AXI_QUAD_SPI_0_AXI4_ADDRESS 0x0
#define XPAR_AXI_QUAD_SPI_0_XIP_MODE 0x0
#define XPAR_AXI_QUAD_SPI_0_STARTUP_BLOCK 0x1
#define XPAR_AXI_QUAD_SPI_0_FIFO_SIZE 0x10

/* Canonical definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_XSPI_0_AXI4_ADDRESS 0x0
#define XPAR_XSPI_0_BASEADDR 0x44a20000
#define XPAR_XSPI_0_HIGHADDR 0x44a2ffff
#define XPAR_XSPI_0_AXI_INTERFACE 0x0
#define XPAR_XSPI_0_BITS_PER_WORD 0x8
#define XPAR_XSPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_XSPI_0_FIFO_SIZE 0x10
#define XPAR_XSPI_0_HASFIFOS 0x1
#define XPAR_XSPI_0_NUM_SS_BITS 0x1
#define XPAR_XSPI_0_SLAVEONLY 0x0
#define XPAR_XSPI_0_SPI_MODE 0x2
#define XPAR_XSPI_0_STARTUP_BLOCK 0x1
#define XPAR_XSPI_0_XIP_MODE 0x0

#define XPAR_XSYSMON_NUM_INSTANCES 1

/* Definitions for peripheral XADC_WIZ_0 */
#define XPAR_XADC_WIZ_0_COMPATIBLE "xlnx,xadc-wiz-3.3"
#define XPAR_XADC_WIZ_0_BASEADDR 0x44a30000
#define XPAR_XADC_WIZ_0_HIGHADDR 0x44a3ffff
#define XPAR_XADC_WIZ_0_INCLUDE_INTR 0x1
#define XPAR_XADC_WIZ_0_IP_TYPE 0x0

/* Canonical definitions for peripheral XADC_WIZ_0 */
#define XPAR_XSYSMON_0_BASEADDR 0x44a30000
#define XPAR_XSYSMON_0_HIGHADDR 0x44a3ffff
#define XPAR_XSYSMON_0_COMPATIBLE "xlnx,xadc-wiz-3.3"
#define XPAR_XSYSMON_0_INCLUDE_INTR 0x1
#define XPAR_XSYSMON_0_IP_TYPE 0x0

#define XPAR_XTMRCTR_NUM_INSTANCES 6

/* Definitions for peripheral PWM_0 */
#define XPAR_PWM_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_PWM_0_BASEADDR 0x41c10000
#define XPAR_PWM_0_HIGHADDR 0x41c1ffff
#define XPAR_PWM_0_CLOCK_FREQUENCY 0x5f5e100

/* Canonical definitions for peripheral PWM_0 */
#define XPAR_XTMRCTR_0_BASEADDR 0x41c10000
#define XPAR_XTMRCTR_0_HIGHADDR 0x41c1ffff
#define XPAR_XTMRCTR_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_0_CLOCK_FREQUENCY 0x5f5e100

/* Definitions for peripheral PWM_1 */
#define XPAR_PWM_1_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_PWM_1_BASEADDR 0x41c20000
#define XPAR_PWM_1_HIGHADDR 0x41c2ffff
#define XPAR_PWM_1_CLOCK_FREQUENCY 0x5f5e100

/* Canonical definitions for peripheral PWM_1 */
#define XPAR_XTMRCTR_1_BASEADDR 0x41c20000
#define XPAR_XTMRCTR_1_HIGHADDR 0x41c2ffff
#define XPAR_XTMRCTR_1_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_1_CLOCK_FREQUENCY 0x5f5e100

/* Definitions for peripheral PWM_2 */
#define XPAR_PWM_2_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_PWM_2_BASEADDR 0x41c30000
#define XPAR_PWM_2_HIGHADDR 0x41c3ffff
#define XPAR_PWM_2_CLOCK_FREQUENCY 0x5f5e100

/* Canonical definitions for peripheral PWM_2 */
#define XPAR_XTMRCTR_2_BASEADDR 0x41c30000
#define XPAR_XTMRCTR_2_HIGHADDR 0x41c3ffff
#define XPAR_XTMRCTR_2_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_2_CLOCK_FREQUENCY 0x5f5e100

/* Definitions for peripheral TIMER_0 */
#define XPAR_TIMER_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_TIMER_0_BASEADDR 0x41c00000
#define XPAR_TIMER_0_HIGHADDR 0x41c0ffff
#define XPAR_TIMER_0_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_TIMER_0_INTERRUPTS 0x2000
#define XPAR_FABRIC_TIMER_0_INTR 0
#define XPAR_TIMER_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral TIMER_0 */
#define XPAR_XTMRCTR_3_BASEADDR 0x41c00000
#define XPAR_FABRIC_XTMRCTR_3_INTR 0
#define XPAR_XTMRCTR_3_HIGHADDR 0x41c0ffff
#define XPAR_XTMRCTR_3_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_3_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_XTMRCTR_3_INTERRUPTS 0x2000
#define XPAR_XTMRCTR_3_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral TIMER_1 */
#define XPAR_TIMER_1_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_TIMER_1_BASEADDR 0x41c40000
#define XPAR_TIMER_1_HIGHADDR 0x41c4ffff
#define XPAR_TIMER_1_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_TIMER_1_INTERRUPTS 0x2001
#define XPAR_FABRIC_TIMER_1_INTR 1
#define XPAR_TIMER_1_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral TIMER_1 */
#define XPAR_XTMRCTR_4_BASEADDR 0x41c40000
#define XPAR_FABRIC_XTMRCTR_4_INTR 1
#define XPAR_XTMRCTR_4_HIGHADDR 0x41c4ffff
#define XPAR_XTMRCTR_4_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_4_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_XTMRCTR_4_INTERRUPTS 0x2001
#define XPAR_XTMRCTR_4_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral TIMER_2 */
#define XPAR_TIMER_2_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_TIMER_2_BASEADDR 0x41c50000
#define XPAR_TIMER_2_HIGHADDR 0x41c5ffff
#define XPAR_TIMER_2_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_TIMER_2_INTERRUPTS 0x2002
#define XPAR_FABRIC_TIMER_2_INTR 2
#define XPAR_TIMER_2_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral TIMER_2 */
#define XPAR_XTMRCTR_5_BASEADDR 0x41c50000
#define XPAR_FABRIC_XTMRCTR_5_INTR 2
#define XPAR_XTMRCTR_5_HIGHADDR 0x41c5ffff
#define XPAR_XTMRCTR_5_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_5_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_XTMRCTR_5_INTERRUPTS 0x2002
#define XPAR_XTMRCTR_5_INTERRUPT_PARENT 0x41200001

#define XPAR_XUARTNS550_NUM_INSTANCES 2

/* Definitions for peripheral UART_1 */
#define XPAR_UART_1_COMPATIBLE "xlnx,axi-uart16550-2.0"
#define XPAR_UART_1_BASEADDR 0x44a10000
#define XPAR_UART_1_HIGHADDR 0x44a1ffff
#define XPAR_UART_1_CLOCK_FREQ 0x5f5e100
#define XPAR_UART_1_INTERRUPTS 0x2003
#define XPAR_FABRIC_UART_1_INTR 3
#define XPAR_UART_1_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral UART_1 */
#define XPAR_XUARTNS550_0_BASEADDR 0x44a10000
#define XPAR_FABRIC_XUARTNS550_0_INTR 3
#define XPAR_XUARTNS550_0_HIGHADDR 0x44a1ffff
#define XPAR_XUARTNS550_0_COMPATIBLE "xlnx,axi-uart16550-2.0"
#define XPAR_XUARTNS550_0_CLOCK_FREQ 0x5f5e100
#define XPAR_XUARTNS550_0_INTERRUPTS 0x2003
#define XPAR_XUARTNS550_0_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral UART_USB */
#define XPAR_UART_USB_COMPATIBLE "xlnx,axi-uart16550-2.0"
#define XPAR_UART_USB_BASEADDR 0x44a00000
#define XPAR_UART_USB_HIGHADDR 0x44a0ffff
#define XPAR_UART_USB_CLOCK_FREQ 0x5f5e100
#define XPAR_UART_USB_INTERRUPTS 0x2004
#define XPAR_FABRIC_UART_USB_INTR 4
#define XPAR_UART_USB_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral UART_USB */
#define XPAR_XUARTNS550_1_BASEADDR 0x44a00000
#define XPAR_FABRIC_XUARTNS550_1_INTR 4
#define XPAR_XUARTNS550_1_HIGHADDR 0x44a0ffff
#define XPAR_XUARTNS550_1_COMPATIBLE "xlnx,axi-uart16550-2.0"
#define XPAR_XUARTNS550_1_CLOCK_FREQ 0x5f5e100
#define XPAR_XUARTNS550_1_INTERRUPTS 0x2004
#define XPAR_XUARTNS550_1_INTERRUPT_PARENT 0x41200001

/*  BOARD definition */
#define XPS_BOARD_CMOD_A7-35T

#define XPAR_AXI_EMC_0_BASEADDRESS 0x60000000
#define XPAR_AXI_EMC_0_HIGHADDRESS 0x61ffffff
#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x1ffff

/*  CPU parameters definition */
#define XPAR_MICROBLAZE_RISCV_TIMEBASE_FREQUENCY 100000000
#define XPAR_MICROBLAZE_RISCV_FREQ 100000000
#define XPAR_MICROBLAZE_RISCV_BASE_VECTORS 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_MULDIV 2
#define XPAR_MICROBLAZE_RISCV_USE_ATOMIC 0
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_D_CACHE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_D_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_RISCV_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_D_CACHE_BASEADDR 0
#define XPAR_MICROBLAZE_RISCV_D_CACHE_HIGHADDR 1073741823
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_REG 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0

#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0

#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_FPU 0

#define XPAR_MICROBLAZE_RISCV_USE_MMU 0

#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0

#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0

#define XPAR_MICROBLAZE_RISCV_D_LMB 1

#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0

#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

#define XPAR_MICROBLAZE_RISCV_ADDR_SIZE 32

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a35t"

#endif  /* end of protection macro */